import { PERMISSIONS, type ROLES } from "../constants";

export type RoleCode = (typeof ROLES)[keyof typeof ROLES];
export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ROLE_PERMISSIONS: Record<RoleCode, PermissionCode[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: Object.values(PERMISSIONS),
  MANAGER: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.ITEM_READ,
    PERMISSIONS.ITEM_WRITE,
    PERMISSIONS.BUSINESS_PARTNER_READ,
    PERMISSIONS.BUSINESS_PARTNER_WRITE,
    PERMISSIONS.PRICE_LIST_READ,
    PERMISSIONS.PRICE_LIST_WRITE,
    PERMISSIONS.TECHNICAL_STANDARD_READ,
    PERMISSIONS.TECHNICAL_STANDARD_WRITE,
    PERMISSIONS.UNIT_OF_MEASURE_READ,
    PERMISSIONS.UNIT_OF_MEASURE_WRITE,
    PERMISSIONS.COMMERCIAL_TERM_READ,
    PERMISSIONS.COMMERCIAL_TERM_WRITE,
    PERMISSIONS.DOCUMENT_SEQUENCE_READ,
    PERMISSIONS.DOCUMENT_SEQUENCE_WRITE,
    PERMISSIONS.PROJECT_OPPORTUNITY_READ,
    PERMISSIONS.PROJECT_OPPORTUNITY_WRITE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_WRITE,
    PERMISSIONS.PROJECT_VISIT_READ,
    PERMISSIONS.PROJECT_VISIT_WRITE,
    PERMISSIONS.PROJECT_RISK_READ,
    PERMISSIONS.PROJECT_RISK_WRITE,
  ],
  MEMBER: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.ITEM_READ,
    PERMISSIONS.BUSINESS_PARTNER_READ,
    PERMISSIONS.PROJECT_OPPORTUNITY_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_VISIT_READ,
    PERMISSIONS.PROJECT_RISK_READ,
  ],
  VIEWER: [],
};

export function permissionsForRole(role: RoleCode): PermissionCode[] {
  return ROLE_PERMISSIONS[role] ?? [];
}

export function hasPermission(roles: RoleCode[], required: PermissionCode): boolean {
  return roles.some((role) => permissionsForRole(role).includes(required));
}
