/**
 * Sprint 3A - 统一 API 错误码常量
 * 所有平台 API 必须使用这里的错误码，禁止散落魔法字符串。
 */
export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // Workflow Definition
  WORKFLOW_DEFINITION_NOT_FOUND: "WORKFLOW_DEFINITION_NOT_FOUND",
  WORKFLOW_DEFINITION_CODE_EXISTS: "WORKFLOW_DEFINITION_CODE_EXISTS",
  WORKFLOW_DEFINITION_PUBLISHED: "WORKFLOW_DEFINITION_PUBLISHED",
  WORKFLOW_DEFINITION_ARCHIVED: "WORKFLOW_DEFINITION_ARCHIVED",
  WORKFLOW_DEFINITION_NO_STEPS: "WORKFLOW_DEFINITION_NO_STEPS",

  // Workflow Instance
  WORKFLOW_INSTANCE_NOT_FOUND: "WORKFLOW_INSTANCE_NOT_FOUND",
  WORKFLOW_INSTANCE_EXISTS: "WORKFLOW_INSTANCE_EXISTS",
  WORKFLOW_INSTANCE_CLOSED: "WORKFLOW_INSTANCE_CLOSED",
  WORKFLOW_INSTANCE_NOT_RUNNING: "WORKFLOW_INSTANCE_NOT_RUNNING",
  WORKFLOW_ACTION_INVALID: "WORKFLOW_ACTION_INVALID",
  WORKFLOW_ACTION_FORBIDDEN: "WORKFLOW_ACTION_FORBIDDEN",
  WORKFLOW_STEP_NOT_FOUND: "WORKFLOW_STEP_NOT_FOUND",
  WORKFLOW_TARGET_REQUIRED: "WORKFLOW_TARGET_REQUIRED",

  // Platform config
  APPROVER_GROUP_NOT_FOUND: "APPROVER_GROUP_NOT_FOUND",
  APPROVER_GROUP_CODE_EXISTS: "APPROVER_GROUP_CODE_EXISTS",
  DICTIONARY_TYPE_NOT_FOUND: "DICTIONARY_TYPE_NOT_FOUND",
  DICTIONARY_TYPE_CODE_EXISTS: "DICTIONARY_TYPE_CODE_EXISTS",
  DICTIONARY_ITEM_NOT_FOUND: "DICTIONARY_ITEM_NOT_FOUND",
  DICTIONARY_ITEM_CODE_EXISTS: "DICTIONARY_ITEM_CODE_EXISTS",
  SETTING_NOT_FOUND: "SETTING_NOT_FOUND",
  SETTING_KEY_EXISTS: "SETTING_KEY_EXISTS",
  NOTIFICATION_TEMPLATE_NOT_FOUND: "NOTIFICATION_TEMPLATE_NOT_FOUND",
  NOTIFICATION_TEMPLATE_CODE_EXISTS: "NOTIFICATION_TEMPLATE_CODE_EXISTS",

  // Quotation（Sprint 4A）
  QUOTATION_NOT_FOUND: "QUOTATION_NOT_FOUND",
  QUOTATION_NOT_EDITABLE: "QUOTATION_NOT_EDITABLE",
  QUOTATION_NO_LINES: "QUOTATION_NO_LINES",
  QUOTATION_EXPIRED: "QUOTATION_EXPIRED",
  QUOTATION_ALREADY_CONVERTED: "QUOTATION_ALREADY_CONVERTED",
  QUOTATION_INVALID_STATE: "QUOTATION_INVALID_STATE",
  QUOTATION_LINE_NOT_FOUND: "QUOTATION_LINE_NOT_FOUND",
  QUOTATION_PRICE_FAILED: "QUOTATION_PRICE_FAILED",
  QUOTATION_WORKFLOW_FAILED: "QUOTATION_WORKFLOW_FAILED",
  QUOTATION_APPROVAL_POLICY_NOT_FOUND: "QUOTATION_APPROVAL_POLICY_NOT_FOUND",
  QUOTATION_OVERRIDE_PRICE_FORBIDDEN: "QUOTATION_OVERRIDE_PRICE_FORBIDDEN",

  // Sales Order（Sprint 4B）
  SALES_ORDER_NOT_FOUND: "SALES_ORDER_NOT_FOUND",
  SALES_ORDER_NOT_EDITABLE: "SALES_ORDER_NOT_EDITABLE",
  SALES_ORDER_INVALID_STATE: "SALES_ORDER_INVALID_STATE",
  SALES_ORDER_LINE_NOT_FOUND: "SALES_ORDER_LINE_NOT_FOUND",
  SALES_ORDER_PRICE_FORBIDDEN: "SALES_ORDER_PRICE_FORBIDDEN",
  SALES_ORDER_PRICE_FAILED: "SALES_ORDER_PRICE_FAILED",
  SALES_ORDER_WORKFLOW_FAILED: "SALES_ORDER_WORKFLOW_FAILED",

  // Delivery（Sprint 4C）
  DELIVERY_NOT_FOUND: "DELIVERY_NOT_FOUND",
  DELIVERY_INVALID_STATE: "DELIVERY_INVALID_STATE",
  DELIVERY_LINE_NOT_FOUND: "DELIVERY_LINE_NOT_FOUND",
  DELIVERY_QUANTITY_EXCEEDED: "DELIVERY_QUANTITY_EXCEEDED",
  DELIVERY_SOURCE_LINE_INVALID: "DELIVERY_SOURCE_LINE_INVALID",
  SALES_ORDER_NOT_DELIVERABLE: "SALES_ORDER_NOT_DELIVERABLE",

  // Invoice（Sprint 4D）
  INVOICE_NOT_FOUND: "INVOICE_NOT_FOUND",
  INVOICE_INVALID_STATE: "INVOICE_INVALID_STATE",
  INVOICE_LINE_NOT_FOUND: "INVOICE_LINE_NOT_FOUND",
  INVOICE_QUANTITY_EXCEEDED: "INVOICE_QUANTITY_EXCEEDED",
  INVOICE_SOURCE_NOT_COMPATIBLE: "INVOICE_SOURCE_NOT_COMPATIBLE",
  INVOICE_WORKFLOW_FAILED: "INVOICE_WORKFLOW_FAILED",

  // Accounts Receivable（Sprint 4E-1；查询/只读，余额由 4E-2/4E-3 动作驱动）
  ACCOUNTS_RECEIVABLE_NOT_FOUND: "ACCOUNTS_RECEIVABLE_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
