/**
 * Sprint 3A - 统一 API 错误码常量
 * 所有平台 API 必须使用这里的错误码，禁止散落魔法字符串。
 */
export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Workflow Definition
  WORKFLOW_DEFINITION_NOT_FOUND: 'WORKFLOW_DEFINITION_NOT_FOUND',
  WORKFLOW_DEFINITION_CODE_EXISTS: 'WORKFLOW_DEFINITION_CODE_EXISTS',
  WORKFLOW_DEFINITION_PUBLISHED: 'WORKFLOW_DEFINITION_PUBLISHED',
  WORKFLOW_DEFINITION_ARCHIVED: 'WORKFLOW_DEFINITION_ARCHIVED',
  WORKFLOW_DEFINITION_NO_STEPS: 'WORKFLOW_DEFINITION_NO_STEPS',

  // Workflow Instance
  WORKFLOW_INSTANCE_NOT_FOUND: 'WORKFLOW_INSTANCE_NOT_FOUND',
  WORKFLOW_INSTANCE_EXISTS: 'WORKFLOW_INSTANCE_EXISTS',
  WORKFLOW_INSTANCE_CLOSED: 'WORKFLOW_INSTANCE_CLOSED',
  WORKFLOW_INSTANCE_NOT_RUNNING: 'WORKFLOW_INSTANCE_NOT_RUNNING',
  WORKFLOW_ACTION_INVALID: 'WORKFLOW_ACTION_INVALID',
  WORKFLOW_ACTION_FORBIDDEN: 'WORKFLOW_ACTION_FORBIDDEN',
  WORKFLOW_STEP_NOT_FOUND: 'WORKFLOW_STEP_NOT_FOUND',
  WORKFLOW_TARGET_REQUIRED: 'WORKFLOW_TARGET_REQUIRED',

  // Platform config
  APPROVER_GROUP_NOT_FOUND: 'APPROVER_GROUP_NOT_FOUND',
  APPROVER_GROUP_CODE_EXISTS: 'APPROVER_GROUP_CODE_EXISTS',
  DICTIONARY_TYPE_NOT_FOUND: 'DICTIONARY_TYPE_NOT_FOUND',
  DICTIONARY_TYPE_CODE_EXISTS: 'DICTIONARY_TYPE_CODE_EXISTS',
  DICTIONARY_ITEM_NOT_FOUND: 'DICTIONARY_ITEM_NOT_FOUND',
  DICTIONARY_ITEM_CODE_EXISTS: 'DICTIONARY_ITEM_CODE_EXISTS',
  SETTING_NOT_FOUND: 'SETTING_NOT_FOUND',
  SETTING_KEY_EXISTS: 'SETTING_KEY_EXISTS',
  NOTIFICATION_TEMPLATE_NOT_FOUND: 'NOTIFICATION_TEMPLATE_NOT_FOUND',
  NOTIFICATION_TEMPLATE_CODE_EXISTS: 'NOTIFICATION_TEMPLATE_CODE_EXISTS',

  // Quotation（Sprint 4A）
  QUOTATION_NOT_FOUND: 'QUOTATION_NOT_FOUND',
  QUOTATION_NOT_EDITABLE: 'QUOTATION_NOT_EDITABLE',
  QUOTATION_NO_LINES: 'QUOTATION_NO_LINES',
  QUOTATION_EXPIRED: 'QUOTATION_EXPIRED',
  QUOTATION_ALREADY_CONVERTED: 'QUOTATION_ALREADY_CONVERTED',
  QUOTATION_INVALID_STATE: 'QUOTATION_INVALID_STATE',
  QUOTATION_LINE_NOT_FOUND: 'QUOTATION_LINE_NOT_FOUND',
  QUOTATION_PRICE_FAILED: 'QUOTATION_PRICE_FAILED',
  QUOTATION_WORKFLOW_FAILED: 'QUOTATION_WORKFLOW_FAILED',
  QUOTATION_APPROVAL_POLICY_NOT_FOUND: 'QUOTATION_APPROVAL_POLICY_NOT_FOUND',
  QUOTATION_OVERRIDE_PRICE_FORBIDDEN: 'QUOTATION_OVERRIDE_PRICE_FORBIDDEN',

  // Sales Order（Sprint 4B）
  SALES_ORDER_NOT_FOUND: 'SALES_ORDER_NOT_FOUND',
  SALES_ORDER_NOT_EDITABLE: 'SALES_ORDER_NOT_EDITABLE',
  SALES_ORDER_INVALID_STATE: 'SALES_ORDER_INVALID_STATE',
  SALES_ORDER_LINE_NOT_FOUND: 'SALES_ORDER_LINE_NOT_FOUND',
  SALES_ORDER_PRICE_FORBIDDEN: 'SALES_ORDER_PRICE_FORBIDDEN',
  SALES_ORDER_PRICE_FAILED: 'SALES_ORDER_PRICE_FAILED',
  SALES_ORDER_WORKFLOW_FAILED: 'SALES_ORDER_WORKFLOW_FAILED',

  // Delivery（Sprint 4C）
  DELIVERY_NOT_FOUND: 'DELIVERY_NOT_FOUND',
  DELIVERY_INVALID_STATE: 'DELIVERY_INVALID_STATE',
  DELIVERY_LINE_NOT_FOUND: 'DELIVERY_LINE_NOT_FOUND',
  DELIVERY_QUANTITY_EXCEEDED: 'DELIVERY_QUANTITY_EXCEEDED',
  DELIVERY_SOURCE_LINE_INVALID: 'DELIVERY_SOURCE_LINE_INVALID',
  SALES_ORDER_NOT_DELIVERABLE: 'SALES_ORDER_NOT_DELIVERABLE',

  // Invoice（Sprint 4D）
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  INVOICE_INVALID_STATE: 'INVOICE_INVALID_STATE',
  INVOICE_LINE_NOT_FOUND: 'INVOICE_LINE_NOT_FOUND',
  INVOICE_QUANTITY_EXCEEDED: 'INVOICE_QUANTITY_EXCEEDED',
  INVOICE_SOURCE_NOT_COMPATIBLE: 'INVOICE_SOURCE_NOT_COMPATIBLE',
  INVOICE_WORKFLOW_FAILED: 'INVOICE_WORKFLOW_FAILED',

  // Accounts Receivable（Sprint 4E-1；查询/只读，余额由 4E-2/4E-3 动作驱动）
  ACCOUNTS_RECEIVABLE_NOT_FOUND: 'ACCOUNTS_RECEIVABLE_NOT_FOUND',

  // Receipt / Payment Allocation（Sprint 4E-2；CTO Design Review 97/100 锁定）
  RECEIPT_NOT_FOUND: 'RECEIPT_NOT_FOUND',
  RECEIPT_CUSTOMER_NOT_FOUND: 'RECEIPT_CUSTOMER_NOT_FOUND',
  RECEIPT_CUSTOMER_MISMATCH: 'RECEIPT_CUSTOMER_MISMATCH',
  RECEIPT_CURRENCY_MISMATCH: 'RECEIPT_CURRENCY_MISMATCH',
  RECEIPT_UNALLOCATED_EXCEEDED: 'RECEIPT_UNALLOCATED_EXCEEDED',
  RECEIPT_ALLOCATION_EXCEEDED: 'RECEIPT_ALLOCATION_EXCEEDED',
  RECEIPT_VOID_FORBIDDEN: 'RECEIPT_VOID_FORBIDDEN',
  RECEIPT_ALLOCATION_NOT_FOUND: 'RECEIPT_ALLOCATION_NOT_FOUND',
  RECEIPT_ALLOCATION_REVERSED: 'RECEIPT_ALLOCATION_REVERSED',

  // WriteOff（Sprint 4E-2；独立事实，禁 PATCH AR.writeOffAmount）
  WRITE_OFF_NOT_FOUND: 'WRITE_OFF_NOT_FOUND',
  WRITE_OFF_EXCEEDED: 'WRITE_OFF_EXCEEDED',
  WRITE_OFF_INVALID_STATE: 'WRITE_OFF_INVALID_STATE',
  WRITE_OFF_ALREADY_APPLIED: 'WRITE_OFF_ALREADY_APPLIED',
  WRITE_OFF_WORKFLOW_FAILED: 'WRITE_OFF_WORKFLOW_FAILED',
  WRITE_OFF_AMOUNT_EXCEEDED: 'WRITE_OFF_AMOUNT_EXCEEDED',
  WRITE_OFF_APPROVAL_REQUIRED: 'WRITE_OFF_APPROVAL_REQUIRED',
  WRITE_OFF_SOURCE_NOT_COMPATIBLE: 'WRITE_OFF_SOURCE_NOT_COMPATIBLE',

  // Sprint 4E-3：Credit Note / Debit Note（发票调整域）
  CN_DN_NOT_FOUND: 'CN_DN_NOT_FOUND',
  CN_DN_SOURCE_INVOICE_INVALID: 'CN_DN_SOURCE_INVOICE_INVALID',
  CN_DN_SOURCE_LINE_INVALID: 'CN_DN_SOURCE_LINE_INVALID',
  CN_DN_SOURCE_NOT_COMPATIBLE: 'CN_DN_SOURCE_NOT_COMPATIBLE',
  CN_DN_INVALID_STATE: 'CN_DN_INVALID_STATE',
  CN_DN_QUANTITY_EXCEEDED: 'CN_DN_QUANTITY_EXCEEDED',
  CN_DN_AMOUNT_EXCEEDED: 'CN_DN_AMOUNT_EXCEEDED',
  CN_DN_WORKFLOW_FAILED: 'CN_DN_WORKFLOW_FAILED',
  // Apply 专用（CTO 98/100：APPROVED ≠ APPLIED；重复 Apply 稳定 409）
  CN_DN_ALREADY_APPLIED: 'CN_DN_ALREADY_APPLIED',
  CN_DN_APPROVAL_REQUIRED: 'CN_DN_APPROVAL_REQUIRED',
  // 负 AR 门禁（CTO 锁死：balance < 0 → 禁 Receipt Allocation / WriteOff）
  RECEIPT_AR_NEGATIVE_BALANCE: 'RECEIPT_AR_NEGATIVE_BALANCE',
  WRITE_OFF_AR_NEGATIVE_BALANCE: 'WRITE_OFF_AR_NEGATIVE_BALANCE',

  // Sprint 5A：Purchase Requisition（PR API Phase 3；PO API 冻结。红线：PR Header/Line 无金额事实）
  PURCHASE_REQUISITION_NOT_FOUND: 'PURCHASE_REQUISITION_NOT_FOUND',
  PURCHASE_REQUISITION_INVALID_STATE: 'PURCHASE_REQUISITION_INVALID_STATE',
  PURCHASE_REQUISITION_NO_LINES: 'PURCHASE_REQUISITION_NO_LINES',
  PURCHASE_REQUISITION_QUANTITY_INVALID: 'PURCHASE_REQUISITION_QUANTITY_INVALID',
  PURCHASE_REQUISITION_ITEM_NOT_FOUND: 'PURCHASE_REQUISITION_ITEM_NOT_FOUND',
  PURCHASE_REQUISITION_UOM_NOT_FOUND: 'PURCHASE_REQUISITION_UOM_NOT_FOUND',
  PURCHASE_REQUISITION_APPROVAL_POLICY_NOT_FOUND: 'PURCHASE_REQUISITION_APPROVAL_POLICY_NOT_FOUND',
  PURCHASE_REQUISITION_WORKFLOW_FAILED: 'PURCHASE_REQUISITION_WORKFLOW_FAILED',

  // Sprint 5A：Purchase Order（PO API Phase 4A：Create/Convert/Query/PATCH；PO=采购承诺事实源，金额服务端聚合）
  PURCHASE_ORDER_NOT_FOUND: 'PURCHASE_ORDER_NOT_FOUND',
  PURCHASE_ORDER_INVALID_STATE: 'PURCHASE_ORDER_INVALID_STATE',
  PURCHASE_ORDER_NO_LINES: 'PURCHASE_ORDER_NO_LINES',
  PURCHASE_ORDER_QUANTITY_INVALID: 'PURCHASE_ORDER_QUANTITY_INVALID',
  PURCHASE_ORDER_SUPPLIER_NOT_FOUND: 'PURCHASE_ORDER_SUPPLIER_NOT_FOUND',
  PURCHASE_ORDER_ITEM_NOT_FOUND: 'PURCHASE_ORDER_ITEM_NOT_FOUND',
  PURCHASE_ORDER_UOM_NOT_FOUND: 'PURCHASE_ORDER_UOM_NOT_FOUND',
  // 价格双通道（CTO 拍板③）：SUPPLIER_PRICE_SNAPSHOT 未命中 / MANUAL 缺 priceReason
  PURCHASE_ORDER_PRICE_NOT_FOUND: 'PURCHASE_ORDER_PRICE_NOT_FOUND',
  PURCHASE_ORDER_PRICE_REASON_REQUIRED: 'PURCHASE_ORDER_PRICE_REASON_REQUIRED',
  // Convert（拍板②）：PR 必须 APPROVED 且未转换；PR 无金额事实
  PURCHASE_ORDER_REQUISITION_NOT_APPROVED: 'PURCHASE_ORDER_REQUISITION_NOT_APPROVED',
  PURCHASE_ORDER_REQUISITION_ALREADY_CONVERTED: 'PURCHASE_ORDER_REQUISITION_ALREADY_CONVERTED',
  // PATCH 溯源（Phase 4A Review Blocking ③）：REQUISITION 行必须显式提供且服务端验证 source PR Line；Direct 强制为空
  PURCHASE_ORDER_SOURCE_LINE_REQUIRED: 'PURCHASE_ORDER_SOURCE_LINE_REQUIRED',
  PURCHASE_ORDER_SOURCE_LINE_INVALID: 'PURCHASE_ORDER_SOURCE_LINE_INVALID',
  PURCHASE_ORDER_SOURCE_LINE_FORBIDDEN: 'PURCHASE_ORDER_SOURCE_LINE_FORBIDDEN',
  // Phase 4B（CTO 指令）：Submit/Confirm/Cancel 门禁
  PURCHASE_ORDER_APPROVAL_POLICY_NOT_FOUND: 'PURCHASE_ORDER_APPROVAL_POLICY_NOT_FOUND',
  PURCHASE_ORDER_NOT_APPROVED: 'PURCHASE_ORDER_NOT_APPROVED', // Confirm 前置：仅 APPROVED 可 Confirm
  PURCHASE_ORDER_ALREADY_CONFIRMED: 'PURCHASE_ORDER_ALREADY_CONFIRMED',
  PURCHASE_ORDER_APPROVAL_REQUIRED: 'PURCHASE_ORDER_APPROVAL_REQUIRED', // 命中审批策略但未 APPROVED 时禁止 Confirm
  PURCHASE_ORDER_CANCEL_FORBIDDEN: 'PURCHASE_ORDER_CANCEL_FORBIDDEN', // CONFIRMED+ 禁止 Cancel（CTO Phase 4B）
  PURCHASE_ORDER_WORKFLOW_FAILED: 'PURCHASE_ORDER_WORKFLOW_FAILED',
  // Sprint 5B：PurchaseReceipt（采购收货事实，CTO Phase 2 Review 98/100 后开发，Receive 8 条硬规则）
  PURCHASE_RECEIPT_NOT_FOUND: 'PURCHASE_RECEIPT_NOT_FOUND',
  PURCHASE_RECEIPT_INVALID_STATE: 'PURCHASE_RECEIPT_INVALID_STATE', // 非 DRAFT 操作（PATCH/Receive/Cancel）
  PURCHASE_RECEIPT_NO_LINES: 'PURCHASE_RECEIPT_NO_LINES',
  PURCHASE_RECEIPT_QUANTITY_INVALID: 'PURCHASE_RECEIPT_QUANTITY_INVALID', // quantity <= 0 或 0 <= rejectedOnReceiptQty <= quantity 违反
  PURCHASE_RECEIPT_LINE_NOT_FOUND: 'PURCHASE_RECEIPT_LINE_NOT_FOUND',
  PURCHASE_RECEIPT_LINE_PO_MISMATCH: 'PURCHASE_RECEIPT_LINE_PO_MISMATCH', // 规则②：行必须属于同一 PO
  PURCHASE_RECEIPT_WAREHOUSE_REQUIRED: 'PURCHASE_RECEIPT_WAREHOUSE_REQUIRED', // 规则③：WAREHOUSE 行必须有有效 warehouseId
  PURCHASE_RECEIPT_WAREHOUSE_INVALID: 'PURCHASE_RECEIPT_WAREHOUSE_INVALID',
  PURCHASE_RECEIPT_DUPLICATE_PO_LINE: 'PURCHASE_RECEIPT_DUPLICATE_PO_LINE', // B②：同一 Receipt 内一个 PO Line 只能出现一次
  PURCHASE_RECEIPT_OVER_RECEIPT: 'PURCHASE_RECEIPT_OVER_RECEIPT', // 规则⑤：超收超容差 ceiling（System Default 0%）
  PURCHASE_RECEIPT_ALREADY_RECEIVED: 'PURCHASE_RECEIPT_ALREADY_RECEIVED', // 规则①：RECEIVED PO 禁普通新增收货
  PURCHASE_RECEIPT_CANCEL_FORBIDDEN: 'PURCHASE_RECEIPT_CANCEL_FORBIDDEN', // 已 RECEIVED 禁止 Cancel
  PURCHASE_RECEIPT_PO_NOT_FOUND: 'PURCHASE_RECEIPT_PO_NOT_FOUND',
  PURCHASE_RECEIPT_PO_STATE_FORBIDDEN: 'PURCHASE_RECEIPT_PO_STATE_FORBIDDEN', // 规则①：PO 状态不允许收货（仅 CONFIRMED/PARTIALLY_RECEIVED）
  // Sprint 5B：Inspection（质检唯一事实源，CTO PurchaseReceipt API Final Re-check 97/100 APPROVED #7045 后开发）
  INSPECTION_NOT_FOUND: 'INSPECTION_NOT_FOUND',
  INSPECTION_INVALID_STATE: 'INSPECTION_INVALID_STATE', // 非 PENDING 操作（PATCH/complete 仅 PENDING）
  INSPECTION_ALREADY_EXISTS: 'INSPECTION_ALREADY_EXISTS', // 同一 PurchaseReceiptLine 已存在有效 Inspection（一次检验即最终结果）
  INSPECTION_LINE_NOT_FOUND: 'INSPECTION_LINE_NOT_FOUND', // PurchaseReceiptLine 不存在或已删除
  INSPECTION_LINE_NOT_RECEIVED: 'INSPECTION_LINE_NOT_RECEIVED', // 来源必须是已 RECEIVED 的 PurchaseReceiptLine（CTO #7045）
  INSPECTION_QUANTITY_INVALID: 'INSPECTION_QUANTITY_INVALID', // 数量非法：qualifiedQty/rejectedQty < 0、或 qualifiedQty + rejectedQty ≠ inspectableQty（=）
  INSPECTION_NO_INSPECTABLE_QTY: 'INSPECTION_NO_INSPECTABLE_QTY', // inspectableQty = quantity - rejectedOnReceiptQty <= 0（无对象可检）
  // Sprint 5B：WarehouseReceipt（采购入库事实，CTO Inspection API Final 98/100 APPROVED #7135 后开发；D10：Created ≠ Posted，只有 POSTED 才触发 6A InventoryMovement(IN)）
  WAREHOUSE_RECEIPT_NOT_FOUND: 'WAREHOUSE_RECEIPT_NOT_FOUND',
  WAREHOUSE_RECEIPT_INVALID_STATE: 'WAREHOUSE_RECEIPT_INVALID_STATE', // 非 DRAFT 操作（PATCH/Post）；或已 CANCELLED
  WAREHOUSE_RECEIPT_ALREADY_POSTED: 'WAREHOUSE_RECEIPT_ALREADY_POSTED', // 幂等：已 POSTED 禁止重复 Post
  WAREHOUSE_RECEIPT_NO_LINES: 'WAREHOUSE_RECEIPT_NO_LINES',
  WAREHOUSE_RECEIPT_DUPLICATE_LINE: 'WAREHOUSE_RECEIPT_DUPLICATE_LINE', // 同一入库单内一个收货行只能出现一次
  WAREHOUSE_RECEIPT_PURCHASE_RECEIPT_NOT_RECEIVED:
    'WAREHOUSE_RECEIPT_PURCHASE_RECEIPT_NOT_RECEIVED', // 来源收货单必须已 RECEIVED
  WAREHOUSE_RECEIPT_LINE_NOT_FOUND: 'WAREHOUSE_RECEIPT_LINE_NOT_FOUND', // PurchaseReceiptLine 不存在或已删除
  WAREHOUSE_RECEIPT_LINE_MISMATCH: 'WAREHOUSE_RECEIPT_LINE_MISMATCH', // 行不属于该收货单（PO）
  WAREHOUSE_RECEIPT_INSPECTION_NOT_FOUND: 'WAREHOUSE_RECEIPT_INSPECTION_NOT_FOUND', // Inspection 不存在或已删除
  WAREHOUSE_RECEIPT_INSPECTION_NOT_COMPLETED: 'WAREHOUSE_RECEIPT_INSPECTION_NOT_COMPLETED', // 来源 Inspection 必须已完成（result ≠ PENDING）
  WAREHOUSE_RECEIPT_INSPECTION_NO_QUALIFIED: 'WAREHOUSE_RECEIPT_INSPECTION_NO_QUALIFIED', // qualifiedQty <= 0（无可入库合格数量）
  WAREHOUSE_RECEIPT_INSPECTION_MISMATCH: 'WAREHOUSE_RECEIPT_INSPECTION_MISMATCH', // Inspection 不属于同一收货行（组合 FK 语义）
  WAREHOUSE_RECEIPT_QUANTITY_INVALID: 'WAREHOUSE_RECEIPT_QUANTITY_INVALID', // quantity <= 0 或超过可入库余额
  WAREHOUSE_RECEIPT_OVER_INSPECTION_BALANCE: 'WAREHOUSE_RECEIPT_OVER_INSPECTION_BALANCE', // 累计入库超过 Inspection 可入库余额（qualifiedQty - 已占用）
  WAREHOUSE_RECEIPT_WAREHOUSE_INVALID: 'WAREHOUSE_RECEIPT_WAREHOUSE_INVALID', // 仓库不存在或已停用
  WAREHOUSE_RECEIPT_LOCATION_INVALID: 'WAREHOUSE_RECEIPT_LOCATION_INVALID', // 库位不存在、停用或不属于该仓库
  WAREHOUSE_RECEIPT_DIRECT_PROJECT_FORBIDDEN: 'WAREHOUSE_RECEIPT_DIRECT_PROJECT_FORBIDDEN', // DIRECT_PROJECT（直送）禁入库（P4）
  // Sprint 5B：PurchaseReturn（采购退货独立事实，CTO WarehouseReceipt Final Re-review 98/100 APPROVED #7219 后开发；P5 Final：非负 GR + 必须有来源 + disposition）
  PURCHASE_RETURN_NOT_FOUND: 'PURCHASE_RETURN_NOT_FOUND',
  PURCHASE_RETURN_INVALID_STATE: 'PURCHASE_RETURN_INVALID_STATE', // 非 DRAFT 操作（PATCH/Return）；或已 CANCELLED
  PURCHASE_RETURN_ALREADY_RETURNED: 'PURCHASE_RETURN_ALREADY_RETURNED', // 幂等：已 RETURNED 禁止重复 Return
  PURCHASE_RETURN_NO_LINES: 'PURCHASE_RETURN_NO_LINES',
  PURCHASE_RETURN_DUPLICATE_LINE: 'PURCHASE_RETURN_DUPLICATE_LINE', // 同一退货单内一个来源只能出现一次（防并发超退）
  PURCHASE_RETURN_SOURCE_INVALID: 'PURCHASE_RETURN_SOURCE_INVALID', // 来源不存在或已删除
  PURCHASE_RETURN_SOURCE_MISMATCH: 'PURCHASE_RETURN_SOURCE_MISMATCH', // sourceRefType 与 FK 不匹配 / 来源不属于该 PO
  PURCHASE_RETURN_SOURCE_NOT_RETURNABLE: 'PURCHASE_RETURN_SOURCE_NOT_RETURNABLE', // WAREHOUSE_RECEIPT_LINE 来源必须来自 POSTED 入库事实（CTO #7219）
  PURCHASE_RETURN_QUANTITY_INVALID: 'PURCHASE_RETURN_QUANTITY_INVALID', // quantity <= 0
  PURCHASE_RETURN_OVER_SOURCE_BALANCE: 'PURCHASE_RETURN_OVER_SOURCE_BALANCE', // 退货数量超过来源可退余额（累计 RETURNED 防并发超退）

  // Inventory Ledger Outbox Writer（6A Phase 2，CTO #7543）
  INVENTORY_DIMENSION_INCOMPLETE: 'INVENTORY_DIMENSION_INCOMPLETE', // 库存触发点 canonical dimensions 不完整（itemId/warehouseId/quantity）——poison Outbox 防线，409
  INVENTORY_SERIAL_QTY_MISMATCH: 'INVENTORY_SERIAL_QTY_MISMATCH', // serial-managed：serialNos.length != quantity（数量守恒），409
  INVENTORY_SERIAL_DUPLICATE: 'INVENTORY_SERIAL_DUPLICATE', // serialNos 内重复 serial，409
  INVENTORY_SERIAL_REQUIRED: 'INVENTORY_SERIAL_REQUIRED', // serial-managed 已入库退货必须显式提交本次退货 serialNos（禁 fallback 全来源），409
  INVENTORY_SERIAL_SOURCE_MISMATCH: 'INVENTORY_SERIAL_SOURCE_MISMATCH', // 非 serial-managed 来源禁止提交 serialNos（来源无 serial → 只能 BULK OUT；审计事实一致性，CTO #7574），409
  // Inventory Ledger Consumer（6A Phase 2 第二步，CTO #7588）
  INVENTORY_OUTBOX_PAYLOAD_INVALID: 'INVENTORY_OUTBOX_PAYLOAD_INVALID', // Outbox payload 缺失/类型错误（永久失败 → DEAD_LETTER），409
  INVENTORY_SOURCE_NOT_FOUND: 'INVENTORY_SOURCE_NOT_FOUND', // resolve source：来源单据不存在或状态不符（永久失败 → DEAD_LETTER），409
  INVENTORY_INSUFFICIENT_STOCK: 'INVENTORY_INSUFFICIENT_STOCK', // OUT 余额不足（业务失败 → retry 退避 → 超阈值 DEAD_LETTER；Movement 不写/Projection 不变/Outbox 不误标 PROCESSED），409

  // Sprint 6B：Inventory Transfer（调拨 Vertical Slice，CTO 6B-2 授权）
  INVENTORY_TRANSFER_NOT_FOUND: 'INVENTORY_TRANSFER_NOT_FOUND', // 调拨单不存在或已删除，404
  INVENTORY_TRANSFER_INVALID_STATE: 'INVENTORY_TRANSFER_INVALID_STATE', // 非 DRAFT 操作（PATCH）/ 非 APPROVED 执行 / 已 CANCELLED，409
  INVENTORY_TRANSFER_ALREADY_EXECUTED: 'INVENTORY_TRANSFER_ALREADY_EXECUTED', // 幂等：已 EXECUTED 禁止重复 Execute，409
  INVENTORY_TRANSFER_NO_LINES: 'INVENTORY_TRANSFER_NO_LINES', // 至少一条有效行，400
  INVENTORY_TRANSFER_DUPLICATE_LINE: 'INVENTORY_TRANSFER_DUPLICATE_LINE', // 同一调拨单内 itemId+batchNo+serialNos 组合重复，400
  INVENTORY_TRANSFER_WAREHOUSE_INVALID: 'INVENTORY_TRANSFER_WAREHOUSE_INVALID', // 仓库不存在或已停用，400
  INVENTORY_TRANSFER_LOCATION_INVALID: 'INVENTORY_TRANSFER_LOCATION_INVALID', // 库位不存在、停用或不属于对应仓库（组合 FK），400
  INVENTORY_TRANSFER_SELF_TRANSFER: 'INVENTORY_TRANSFER_SELF_TRANSFER', // 源=目标维度（同仓同库位）自调拨拒绝，409
  INVENTORY_TRANSFER_QUANTITY_INVALID: 'INVENTORY_TRANSFER_QUANTITY_INVALID', // quantity <= 0，400
  INVENTORY_TRANSFER_SERIAL_QTY_MISMATCH: 'INVENTORY_TRANSFER_SERIAL_QTY_MISMATCH', // serial-managed：serialNos.length != quantity（数量守恒），400
  INVENTORY_TRANSFER_SERIAL_DUPLICATE: 'INVENTORY_TRANSFER_SERIAL_DUPLICATE', // serialNos 内重复 serial，400
  INVENTORY_TRANSFER_ITEM_INVALID: 'INVENTORY_TRANSFER_ITEM_INVALID', // item 不存在或已停用，400
  INVENTORY_TRANSFER_APPROVAL_REQUIRED: 'INVENTORY_TRANSFER_APPROVAL_REQUIRED', // Execute 前必须 APPROVED（审批未完成），409
  // CTO Transfer Review Blocking ①：TRF DocumentSequence 缺失 = 部署配置错误（fail closed，禁 fallback 临时编号），500
  INVENTORY_TRANSFER_SEQUENCE_MISSING: 'INVENTORY_TRANSFER_SEQUENCE_MISSING',

  // Sprint 6B-3：Stock Count（盘点实盘事实——本身不产生 Movement；差异经 Adjustment 审批后落账）
  STOCK_COUNT_NOT_FOUND: 'STOCK_COUNT_NOT_FOUND', // 盘点单不存在或已删除，404
  STOCK_COUNT_INVALID_STATE: 'STOCK_COUNT_INVALID_STATE', // 非 DRAFT/COUNTING 操作（PATCH/lines/complete/cancel），409
  STOCK_COUNT_NO_LINES: 'STOCK_COUNT_NO_LINES', // 至少一条有效盘点行，400
  STOCK_COUNT_DUPLICATE_LINE: 'STOCK_COUNT_DUPLICATE_LINE', // 同一盘点单内五维（warehouse/location/item/batch/serial）重复，400
  STOCK_COUNT_QUANTITY_INVALID: 'STOCK_COUNT_QUANTITY_INVALID', // countedQty < 0，400
  STOCK_COUNT_WAREHOUSE_INVALID: 'STOCK_COUNT_WAREHOUSE_INVALID', // 仓库不存在或已停用，400
  STOCK_COUNT_LOCATION_INVALID: 'STOCK_COUNT_LOCATION_INVALID', // 库位不存在、停用或不属于对应仓库（组合 FK），400
  STOCK_COUNT_ITEM_INVALID: 'STOCK_COUNT_ITEM_INVALID', // item 不存在或已停用，400
  STOCK_COUNT_ALREADY_COMPLETED: 'STOCK_COUNT_ALREADY_COMPLETED', // 幂等：已 COMPLETED/ADJUSTED 禁止重复 complete，409
  STOCK_COUNT_SNAPSHOT_MISSING: 'STOCK_COUNT_SNAPSHOT_MISSING', // 盘点行 bookQtyAtCount 未生成（未走快照录入），400
  STOCK_COUNT_SEQUENCE_MISSING: 'STOCK_COUNT_SEQUENCE_MISSING', // CNT DocumentSequence 缺失 = 部署配置错误（fail closed，禁 fallback），500

  // Sprint 6B-3：Inventory Adjustment（受控库存账事实——只能经 Shared LedgerCommand 追加 ADJUSTMENT Movement）
  INVENTORY_ADJUSTMENT_NOT_FOUND: 'INVENTORY_ADJUSTMENT_NOT_FOUND', // 调整单不存在或已删除，404
  INVENTORY_ADJUSTMENT_INVALID_STATE: 'INVENTORY_ADJUSTMENT_INVALID_STATE', // 非 DRAFT 操作（PATCH）/ 非 APPROVED 执行（apply）/ 已 CANCELLED，409
  INVENTORY_ADJUSTMENT_ALREADY_APPLIED: 'INVENTORY_ADJUSTMENT_ALREADY_APPLIED', // 幂等：已 APPLIED 禁止重复 apply，409
  INVENTORY_ADJUSTMENT_NO_LINES: 'INVENTORY_ADJUSTMENT_NO_LINES', // 至少一条有效行，400
  INVENTORY_ADJUSTMENT_DUPLICATE_LINE: 'INVENTORY_ADJUSTMENT_DUPLICATE_LINE', // 同一调整单内五维重复，400
  INVENTORY_ADJUSTMENT_QUANTITY_INVALID: 'INVENTORY_ADJUSTMENT_QUANTITY_INVALID', // quantity <= 0，400
  INVENTORY_ADJUSTMENT_WAREHOUSE_INVALID: 'INVENTORY_ADJUSTMENT_WAREHOUSE_INVALID', // 仓库不存在或已停用，400
  INVENTORY_ADJUSTMENT_LOCATION_INVALID: 'INVENTORY_ADJUSTMENT_LOCATION_INVALID', // 库位不存在、停用或不属于对应仓库（组合 FK），400
  INVENTORY_ADJUSTMENT_ITEM_INVALID: 'INVENTORY_ADJUSTMENT_ITEM_INVALID', // item 不存在或已停用，400
  INVENTORY_ADJUSTMENT_MAKER_CHECKER: 'INVENTORY_ADJUSTMENT_MAKER_CHECKER', // maker-checker：创建人与批准/Apply 人不得相同（P9 Final + DB CHECK 兜底），409
  INVENTORY_ADJUSTMENT_APPROVAL_REQUIRED: 'INVENTORY_ADJUSTMENT_APPROVAL_REQUIRED', // Apply 前必须 APPROVED（审批未完成），409
  INVENTORY_ADJUSTMENT_SOURCE_COUNT_INVALID: 'INVENTORY_ADJUSTMENT_SOURCE_COUNT_INVALID', // Minor Hardening ②：非空 sourceStockCountLineId 必须属于 sourceStockCountId 指向的盘点单（跨单引用拒绝），400
  INVENTORY_ADJUSTMENT_SOURCE_LINE_ALREADY_SETTLED:
    'INVENTORY_ADJUSTMENT_SOURCE_LINE_ALREADY_SETTLED', // sourceStockCountLineId 已被其他 Adjustment 占用（UNIQUE 防双重入账），409
  INVENTORY_ADJUSTMENT_SEQUENCE_MISSING: 'INVENTORY_ADJUSTMENT_SEQUENCE_MISSING', // ADJ DocumentSequence 缺失 = 部署配置错误（fail closed，禁 fallback），500

  // Sprint 6B-4：Inventory Conversion（同 item Repack/UOM Conversion——P10/P11 Final，CTO #8658 授权）
  INVENTORY_CONVERSION_NOT_FOUND: 'INVENTORY_CONVERSION_NOT_FOUND', // 转换单不存在或已删除，404
  INVENTORY_CONVERSION_INVALID_STATE: 'INVENTORY_CONVERSION_INVALID_STATE', // 非 DRAFT 操作（PATCH）/ 非 SUBMITTED 执行（execute）/ 已 CANCELLED，409
  INVENTORY_CONVERSION_ALREADY_EXECUTED: 'INVENTORY_CONVERSION_ALREADY_EXECUTED', // 幂等：已 EXECUTED 禁止重复 execute，409
  INVENTORY_CONVERSION_NO_LINES: 'INVENTORY_CONVERSION_NO_LINES', // 至少一条有效行，400
  INVENTORY_CONVERSION_LINE_ROLE_REQUIRED: 'INVENTORY_CONVERSION_LINE_ROLE_REQUIRED', // 必须恰好 1 CONSUME + 1 PRODUCE（Blocking ③：UNIQUE(headerId, lineRole)），400
  INVENTORY_CONVERSION_DUPLICATE_LINE: 'INVENTORY_CONVERSION_DUPLICATE_LINE', // 同一转换单内 lineRole 重复（UNIQUE 冲突），400
  INVENTORY_CONVERSION_ITEM_INVALID: 'INVENTORY_CONVERSION_ITEM_INVALID', // item 不存在或已停用，400
  INVENTORY_CONVERSION_BASE_UOM_INVALID: 'INVENTORY_CONVERSION_BASE_UOM_INVALID', // baseUomId != 该 Item 的 inventory/stock UOM（P11 Final Gate，不允许任意 UOM 冒充库存基准），400
  INVENTORY_CONVERSION_UOM_INVALID: 'INVENTORY_CONVERSION_UOM_INVALID', // 行 uomId 不存在或停用，400
  INVENTORY_CONVERSION_RATE_INVALID: 'INVENTORY_CONVERSION_RATE_INVALID', // uomToBaseRate <= 0（DB CHECK + service），400
  INVENTORY_CONVERSION_BASE_QTY_MISMATCH: 'INVENTORY_CONVERSION_BASE_QTY_MISMATCH', // CONSUME.baseQuantity != PRODUCE.baseQuantity（守恒破坏，P11），400
  INVENTORY_CONVERSION_BASE_QTY_INVALID: 'INVENTORY_CONVERSION_BASE_QTY_INVALID', // Execute 重验：行 stored baseQuantity != ROUND_HALF_UP(quantity × uomToBaseRate, 4)（canonical 不符，CTO Conversion Review Blocking ①），400
  INVENTORY_CONVERSION_BATCH_MISMATCH: 'INVENTORY_CONVERSION_BATCH_MISMATCH', // batch 精确继承：CONSUME batch != PRODUCE batch（P5 Final，首版不拆批不换批），400
  INVENTORY_CONVERSION_SAME_ITEM_REQUIRED: 'INVENTORY_CONVERSION_SAME_ITEM_REQUIRED', // 首版 same item（Repack/UOM Conversion；禁止 BOM/组装/拆解/多物料），400
  INVENTORY_CONVERSION_SERIAL_NOT_SUPPORTED: 'INVENTORY_CONVERSION_SERIAL_NOT_SUPPORTED', // serial 不允许重新生成（P5 Final：serial 场景后续阶段），400
  INVENTORY_CONVERSION_WAREHOUSE_INVALID: 'INVENTORY_CONVERSION_WAREHOUSE_INVALID', // 仓库不存在或已停用，400
  INVENTORY_CONVERSION_LOCATION_INVALID: 'INVENTORY_CONVERSION_LOCATION_INVALID', // 库位不存在、停用或不属于对应仓库（组合 FK），400
  INVENTORY_CONVERSION_SEQUENCE_MISSING: 'INVENTORY_CONVERSION_SEQUENCE_MISSING', // CVT DocumentSequence 缺失 = 部署配置错误（fail closed，禁 fallback），500

  // Sprint 5C-1A：Supplier Invoice Foundation（RECEIPT_BASED 首版——PO Line + POSTED WHR Line 双溯源；CTO #9048 FINAL APPROVED）
  SUPPLIER_INVOICE_NOT_FOUND: 'SUPPLIER_INVOICE_NOT_FOUND', // 供应商发票不存在或已删除，404
  SUPPLIER_INVOICE_INVALID_STATE: 'SUPPLIER_INVOICE_INVALID_STATE', // 非 DRAFT 操作（PATCH）/ 非 DRAFT 提交（submit）/ 已取消，409
  SUPPLIER_INVOICE_ALREADY_SUBMITTED: 'SUPPLIER_INVOICE_ALREADY_SUBMITTED', // 幂等：已 SUBMITTED 禁止重复 submit，409
  SUPPLIER_INVOICE_NO_LINES: 'SUPPLIER_INVOICE_NO_LINES', // 至少一条有效行，400
  SUPPLIER_INVOICE_DUPLICATE_LINE: 'SUPPLIER_INVOICE_DUPLICATE_LINE', // 同一发票内 PO Line 重复（同一双溯源行只能开一次票），400
  SUPPLIER_INVOICE_SUPPLIER_INVALID: 'SUPPLIER_INVOICE_SUPPLIER_INVALID', // 供应商不存在或已停用，400
  SUPPLIER_INVOICE_DUPLICATE_NUMBER: 'SUPPLIER_INVOICE_DUPLICATE_NUMBER', // supplierId + supplierInvoiceNo 组合重复（不变量②），409
  SUPPLIER_INVOICE_WHR_NOT_POSTED: 'SUPPLIER_INVOICE_WHR_NOT_POSTED', // RECEIPT_BASED 三重 Gate：WHR header 必须 POSTED（红线 1），400
  SUPPLIER_INVOICE_SOURCE_CHAIN_MISMATCH: 'SUPPLIER_INVOICE_SOURCE_CHAIN_MISMATCH', // WHR Line ↔ PO Line ↔ Item ↔ Supplier 来源链不一致（红线 1），400
  SUPPLIER_INVOICE_ITEM_INVALID: 'SUPPLIER_INVOICE_ITEM_INVALID', // item 不存在或已停用，400
  SUPPLIER_INVOICE_QUANTITY_INVALID: 'SUPPLIER_INVOICE_QUANTITY_INVALID', // 开票数量 <= 0 或超过已入库数量，400
  SUPPLIER_INVOICE_CUMULATIVE_QTY_EXCEEDED: 'SUPPLIER_INVOICE_CUMULATIVE_QTY_EXCEEDED', // 累计开票数量守恒：本次 + 其他非 CANCELLED 发票行占用 > WHR 已入库数量（Blocking ① CTO #9161），400
  SUPPLIER_INVOICE_RATE_INVALID: 'SUPPLIER_INVOICE_RATE_INVALID', // taxRate 不合法，400
  SUPPLIER_INVOICE_SEQUENCE_MISSING: 'SUPPLIER_INVOICE_SEQUENCE_MISSING', // SINV DocumentSequence 缺失 = 部署配置错误（fail closed，禁 fallback），500

  // Sprint 5C-1B：Immutable 3-Way Match（Match 与 Approval 分层——CTO #9238/#9247）
  SUPPLIER_INVOICE_MATCH_NOT_MATCHABLE: 'SUPPLIER_INVOICE_MATCH_NOT_MATCHABLE', // 仅 SUBMITTED/MATCHED 可 Match；APPROVED/POSTED/CANCELLED 禁直接 re-match（#9247），409
  SUPPLIER_INVOICE_MATCH_STALE_APPROVAL: 'SUPPLIER_INVOICE_MATCH_STALE_APPROVAL', // Workflow 审批引用的 run/revision != 当前 currentMatchRun——re-match 后旧审批不得批准新 snapshot（#9247），409
  SUPPLIER_INVOICE_MATCH_NO_LINES: 'SUPPLIER_INVOICE_MATCH_NO_LINES', // Match 时发票无有效行，400

  // Sprint 5C-1C：Supplier Invoice POST / GRIR CONSUME / AP Liability-OpenItem（CTO #9678 六条不变量）
  SUPPLIER_INVOICE_NOT_APPROVED: 'SUPPLIER_INVOICE_NOT_APPROVED', // 仅 APPROVED 可 POST（APPROVED ≠ POSTED），409
  SUPPLIER_INVOICE_ALREADY_POSTED: 'SUPPLIER_INVOICE_ALREADY_POSTED', // 幂等：已 POSTED 重复 POST，409（不会重复生成 Liability/Consume）
  SUPPLIER_INVOICE_APPROVAL_SNAPSHOT_INVALID: 'SUPPLIER_INVOICE_APPROVAL_SNAPSHOT_INVALID', // approvedMatchRunId/approvedMatchRevision 缺失或与审批 immutable snapshot 不一致（#9678 不变量①），409
  SUPPLIER_INVOICE_MAKER_CHECKER: 'SUPPLIER_INVOICE_MAKER_CHECKER', // maker-checker：Poster 不得 = Creator / Approval actor（#9678），409
  SUPPLIER_INVOICE_GRIR_INSUFFICIENT: 'SUPPLIER_INVOICE_GRIR_INSUFFICIENT', // remaining GRIR 不足全额 consume（#9678 不变量③：禁止 partial POST，fail closed），409

  // Sprint 7 VAT 发票管理（ADR-0043：发票类型/税务号码/红字/开票资料）
  INVOICE_TYPE_REQUIRED: 'INVOICE_TYPE_REQUIRED', // ISSUE/POSTED 时发票类型必填（I4，fail closed），409
  TAX_INVOICE_CODE_INVALID: 'TAX_INVOICE_CODE_INVALID', // 税务发票代码格式非法（专/普 12 位；数电票必须为空）（I7），400
  TAX_INVOICE_NO_INVALID: 'TAX_INVOICE_NO_INVALID', // 税务发票号码格式非法（专/普 8 位；数电 20 位）（I7），400
  TAX_INVOICE_NO_DUPLICATE: 'TAX_INVOICE_NO_DUPLICATE', // 税务发票号码组合唯一冲突（I2），409
  USCC_INVALID: 'USCC_INVALID', // 统一社会信用代码非法（GB 32100-2015 18 位校验码）（I1），400
  RED_INVOICE_REF_IMMUTABLE: 'RED_INVOICE_REF_IMMUTABLE', // 红字引用/税务字段不可变（ISSUE/POSTED 后冻结）（I3），409
  RED_INVOICE_REF_STATUS_INVALID: 'RED_INVOICE_REF_STATUS_INVALID', // 红字引用原票必须为终态蓝票，禁链式引用（R2/R6），409
  RED_INVOICE_OVERFLOW: 'RED_INVOICE_OVERFLOW', // 红字累计超冲：Σ|红字| > |原票|（R4，锁内校验），409
  PARTNER_LINK_REQUIRED: 'PARTNER_LINK_REQUIRED', // 开票客户必须关联 BusinessPartner（I10，fail closed），409
  PARTNER_INVOICE_INFO_MISSING: 'PARTNER_INVOICE_INFO_MISSING', // 开票资料缺失（title+uscc 必填）（I10，fail closed），409

  // Sprint 7 会计期间（ADR-0044：期间校验/凭证字/按月编号）
  GL_PERIOD_NOT_FOUND: 'GL_PERIOD_NOT_FOUND', // 会计期间不存在（未 backfill 初始化）（INV1），409
  GL_PERIOD_CLOSED: 'GL_PERIOD_CLOSED', // 期间已结转（CLOSED），禁止过账（INV1），409
  GL_PERIOD_LOCKED: 'GL_PERIOD_LOCKED', // 期间已锁定（LOCKED），禁止过账/结转/重开（INV1），409
  GL_PERIOD_FUTURE: 'GL_PERIOD_FUTURE', // 禁止未来期间过账（INV1），409
  GL_PERIOD_ALREADY_CLOSED: 'GL_PERIOD_ALREADY_CLOSED', // 期间已结转，禁止重复结转（INV8），409
  GL_PERIOD_INVALID: 'GL_PERIOD_INVALID', // 期间格式非法（须 YYYY-MM），400
  GL_VOUCHER_TYPE_INVALID: 'GL_VOUCHER_TYPE_INVALID', // 凭证字非法（记/收/付/转），400
  GL_ATTACHMENT_COUNT_INVALID: 'GL_ATTACHMENT_COUNT_INVALID', // 附件张数非法（0-999），400
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
