/**
 * Sprint 3A - 统一 API 错误码常量
 * 所有平台 API 必须使用这里的错误码，禁止散落魔法字符串。
 */
export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // Workflow Definition
  WORKFLOW_DEFINITION_NOT_FOUND: "WORKFLOW_DEFINITION_NOT_FOUND",
  WORKFLOW_DEFINITION_CODE_EXISTS: "WORKFLOW_DEFINITION_CODE_EXISTS",
  WORKFLOW_DEFINITION_PUBLISHED: "WORKFLOW_DEFINITION_PUBLISHED",
  WORKFLOW_DEFINITION_ARCHIVED: "WORKFLOW_DEFINITION_ARCHIVED",
  WORKFLOW_DEFINITION_NO_STEPS: "WORKFLOW_DEFINITION_NO_STEPS",

  // Workflow Instance
  WORKFLOW_INSTANCE_NOT_FOUND: "WORKFLOW_INSTANCE_NOT_FOUND",
  WORKFLOW_INSTANCE_EXISTS: "WORKFLOW_INSTANCE_EXISTS",
  WORKFLOW_INSTANCE_CLOSED: "WORKFLOW_INSTANCE_CLOSED",
  WORKFLOW_INSTANCE_NOT_RUNNING: "WORKFLOW_INSTANCE_NOT_RUNNING",
  WORKFLOW_ACTION_INVALID: "WORKFLOW_ACTION_INVALID",
  WORKFLOW_ACTION_FORBIDDEN: "WORKFLOW_ACTION_FORBIDDEN",
  WORKFLOW_STEP_NOT_FOUND: "WORKFLOW_STEP_NOT_FOUND",
  WORKFLOW_TARGET_REQUIRED: "WORKFLOW_TARGET_REQUIRED",

  // Platform config
  APPROVER_GROUP_NOT_FOUND: "APPROVER_GROUP_NOT_FOUND",
  APPROVER_GROUP_CODE_EXISTS: "APPROVER_GROUP_CODE_EXISTS",
  DICTIONARY_TYPE_NOT_FOUND: "DICTIONARY_TYPE_NOT_FOUND",
  DICTIONARY_TYPE_CODE_EXISTS: "DICTIONARY_TYPE_CODE_EXISTS",
  DICTIONARY_ITEM_NOT_FOUND: "DICTIONARY_ITEM_NOT_FOUND",
  DICTIONARY_ITEM_CODE_EXISTS: "DICTIONARY_ITEM_CODE_EXISTS",
  SETTING_NOT_FOUND: "SETTING_NOT_FOUND",
  SETTING_KEY_EXISTS: "SETTING_KEY_EXISTS",
  NOTIFICATION_TEMPLATE_NOT_FOUND: "NOTIFICATION_TEMPLATE_NOT_FOUND",
  NOTIFICATION_TEMPLATE_CODE_EXISTS: "NOTIFICATION_TEMPLATE_CODE_EXISTS",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
